Update update.yml

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -1,25 +1,33 @@
 name: Auto Fetch Stream
 
 on:
-  schedule:
-    - cron: "*/5 * * * *"   # ทุก 5 นาที
   workflow_dispatch:
+  schedule:
+    - cron: "*/5 * * * *"
 
 jobs:
   fetch:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout
+        uses: actions/checkout@v3
 
       - name: Fetch m3u8
         run: |
-          curl -s "https://p0.cdn.vet/live/ch3/i/ch3i.m3u8?sid=b5yYTk0OTIwNTIzNDU1Mzg4ODczMQNzExN2JlODIzNWEzNGU4 "> latest.txt
+          URL="https://p0.cdn.vet/live/ch3/i/ch3i.m3u8"
 
-      - name: Commit update
+          curl -L \
+            -H "User-Agent: Mozilla/5.0" \
+            -H "Referer: https://ch3plus.com/" \
+            "$URL" \
+            -o stream.m3u8 || echo "#FAILED" > stream.m3u8
+
+      - name: Commit
         run: |
-          git config user.name github-actions
-          git config user.email actions@github.com
-          git add latest.txt
-          git commit -m "update stream" || exit 0
+          git config --global user.name "bot"
+          git config --global user.email "bot@users.noreply.github.com"
+          git add stream.m3u8
+          git commit -m "update stream" || echo "no change"
           git push
+
